### ISSUE TITLE
阿里云盘已经登录，但还是一直提示请先登录

### ISSUE THREAD

**Issue by noir1216** [hmjz100/Online-disk-direct-link-download-assistant#105]
已经登录的情况下，还是一直提示请先登录
手动退出账号后重新登录也不行
![QQ截图20240724180650](https://github.com/user-attachments/assets/c793a68d-0d59-4aee-bf2d-9fb32d321a3a)

**Comment by hmjz100** [comment]
阿里盘ban分享了，请转存到网盘后再下载
