### ISSUE TITLE
阿里云盘勾选要下载的文件后点击下载助手按钮时依然提示“请先勾选要下载的文件！”

### ISSUE THREAD

**Issue by fhohfguo** [hmjz100/Online-disk-direct-link-download-assistant#11]
https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/91009212/fef00958-d0b8-446c-b239-d6efe3bad934

**Comment by hmjz100** [comment]
已阅，稍后我将跟进最新版本
