### ISSUE TITLE
IDM支持阿里云盘下载吗？

### ISSUE THREAD

**Issue by lim-kim930** [hmjz100/Online-disk-direct-link-download-assistant#111]
将阿里云盘的直链在IDM里创建下载任务报403；

将Referer设置为 https://www.alipan.com/ 和 https://www.aliyundrive.com/ 都没有效果，UA使用的是浏览器UA，不知道还有哪里有问题还是不支持IDM下载

**Comment by lim-kim930** [comment]
看到油小猴的说明了，确实不支持

**Comment by hmjz100** [comment]
其实可以勉强支持，用”直接下载(基于浏览器链接)“的话有可能会被IDM捕获，我这边试过，没报403
