### ISSUE TITLE
下载保存路径

### ISSUE THREAD

**Issue by FHomeworker** [hmjz100/Online-disk-direct-link-download-assistant#117]
我在使用该扩展结合Motrix使用  
我在下载夸克网盘文件时，发现文件它总是会保存到我的D盘下的Downloads文件夹（即使该文件夹被删除，会重新建立），我尝试修改Motrix的下载保存路径，但这毫无作用。看到有人回应说是扩展设置的保存路径优先级比Motrix高。请问这个东西好修改吗？

**Comment by hmjz100** [comment]
很好改呀，就去`下载助手->助手设置->RPC保存->改成你要的路径`就好了

**Comment by FHomeworker** [comment]
非常感谢作者的回复！我起初在油猴脚本页面寻找设置没有找到，后来发现原来在使用时的RPC下载后的有个RPC参数设置，问题已解决，感谢作者的扩展，受益良多！
![Uploading Snipaste_2024-09-02_22-30-55.png…]()
