### ISSUE TITLE
百度网盘获取链接时一直显示链接获取中.....

### ISSUE THREAD

**Issue by endsock** [hmjz100/Online-disk-direct-link-download-assistant#118]
百度网盘获取链接时一直显示链接获取中.....卡住不动，无法使用
并测试了夸克网盘，没有问题

**Comment by ReallyChooseC** [comment]
+1
![image](https://github.com/user-attachments/assets/aca617ae-b8a3-486f-a3ea-c9c77dc3ff31)

**Comment by CreativeZG** [comment]
同样问题

**Comment by hmjz100** [comment]
各位在网盘按下 F12 然后打开控制台，之后获取链接，截图下控制台里红色的报错内容给我分析看看

**Comment by thankyou232** [comment]
![dda26aaabd495ba14328e9a2e671bd4e](https://github.com/user-attachments/assets/cdcf242c-6e79-4bdb-a359-77cdaa9e5d86)
![image](https://github.com/user-attachments/assets/b111440d-6133-47d3-b1a2-36d354f742dc)
涂掉了一些类似access token的东西

**Comment by endsock** [comment]
chrome console控制台显示：
请求地址：https://pan.baidu.com/rest/2.0/xpan/multimedia?method=filemetas&dlink=1&fsids=%5B823088666879491%5D&access_token=xxxxxxxxxxxxxxxxx
返回：
{errno: 9019, errmsg: 'need verify', request_id: 258815936624359000}

**Comment by fisher44123** [comment]
+1

**Comment by hmjz100** [comment]
报错 errno: 9019 是百度封接口了，我这边也没什么办法

**Comment by my-world-only-me** [comment]
可以尝试自行获取Access Token
访问 https://pan.baidu.com/union/doc/0ksg0sbig 创建应用并获取 AppKey，然后替换参数并访问http://openapi.baidu.com/oauth/2.0/authorize?response_type=token&client_id=填你自己的appkey&redirect_uri=oob&scope=basic,netdisk 获取 Access Token，等待脚本自行刷新后就能用了

**Comment by StrollStars** [comment]
@hmjz100 那就是永久失效了？

@my-world-only-me 开放平台现在只能以企业类型接入了？

**Comment by hmjz100** [comment]
emm……也不算”永久失效“，不知道百度最近又在搞什么东东，这个 9019 错误就挺奇怪的，我这边获取文件就正常，不会报 9019。

**Comment by hmjz100** [comment]
这里有一些我收集的 client_id（AppKey），需要的可自取：
`L6g70tBRRIXLsY0Z3HwKqlRE` // pcstest_oauth
`fSds3K4w43rw37tOqlQmTa2kDwaczK4U` // 小度智能词典笔专业版
`TFwtw8uwHxpdkvVqVKdIlx1XqXUnr1zG` // 印象笔记
`9dgBV9yesuBVOXaxls7aVHbLBLqU8yyg` // WPS文档
`l9DdBOG4RYroMscmzK5OChdaGelgd92M` // 小猴云印PC版
`IlLqBbU3GjQ0t46TRwFateTprHWl39zF` // 百度手机助手

**Comment by my-world-only-me** [comment]
@StrollStars 开放平台好像之前确实是停止注册过一段时间, 说是要改。不过我是两年前搞得，所以我也不大清楚是不是只能企业用了

**Comment by ZJDATY** [comment]
+1 可以修复吗

**Comment by StrollStars** [comment]
@hmjz100 @my-world-only-me 感谢分享，确实可用。估计可能是之前用来下大文件，所以出了这个问题。

**Comment by hmjz100** [comment]
各位遇到 9019(或者是卡住获取中) 的朋友们，我似乎摸到了一个解决方法  
打开`油猴编辑此脚本的界面->存储`，在编辑框中删除带有“baidu_access_token”的那一行，然后保存，之后再重新获取直链即可  
各位试成功后记得再此处反馈一声，成功率高的话后续会更新脚本

**Comment by mx440** [comment]
编辑脚本实测有效

**Comment by yeasine** [comment]
> 各位遇到 9019(或者是卡住获取中) 的朋友们，我似乎摸到了一个解决方法 打开`油猴编辑此脚本的界面->存储`，在编辑框中删除带有“baidu_access_token”的那一行，然后保存，之后再重新获取直链即可 各位试成功后记得在此处反馈一声，成功率高的话后续会更新脚本

油猴编辑此脚本的界面->存储  这一步没找到，点编辑就是
![image](https://github.com/user-attachments/assets/533636d0-102d-47cc-a696-83992fb14b16)
这样的界面，能搜到好多“baidu_access_token”

**Comment by yeasine** [comment]
我最近一直都是无限获取中，今天尝试编辑脚本那个没弄明白就点了恢复出厂设置，重新激活一遍脚本竟然就可以再次获取成功了

**Comment by shjohnnyyu** [comment]
正解，重置脚本重新设置，就可恢复正常。

**Comment by liyiwudi1945** [comment]
1.0.9.4更新过后还是不能用

**Comment by hmjz100** [comment]
> 1.0.9.4更新过后还是不能用

控制台截个报错的图看看

**Comment by hmjz100** [comment]
这是百度的问题了，我也没办法

**Comment by B0idmachine** [comment]
同样的情况，也是百度出问题了吗？
![image](https://github.com/user-attachments/assets/5dc218ed-0b8d-4cef-b6ce-759c2fdd4bb8)

**Comment by asteroideauwu** [comment]
这里更新后似乎还是无法获取链接

**Comment by tester00688** [comment]
链接获取中............

**Comment by hmjz100** [comment]
各位，我又想了一些方法，如果可以的话，请试下：
1. 打开 “[https://passport.baidu.com/accountbind](https://passport.baidu.com/accountbind)” 页面，解除 “百度手机助手” 的关联  
之后等一小段时间，等到 AccessToken 过期（时间不清楚，不过可以通过重置脚本来快速删除脚本正在使用的 AccessToken），  
然后重新走一遍刚开始的流程……获取链接……授权脚本……获取链接……可能就能使用了  
  
2. 换掉可以换的东西，比如浏览器啊、百度网盘的账号啊之类的
  
Q: 为什么是 “百度手机助手”？  
A: 脚本使用的接口的应用 id 是 “百度手机助手” 的，故为这个名字

**Comment by B0idmachine** [comment]
![image](https://github.com/user-attachments/assets/18d9b1e8-73ac-4ccb-bbc1-6ac3db4ec571)
方法1不行

**Comment by Ai-Himmel** [comment]
根据Tempermonkey的更新日志
>5.3.0
>2024-09-15
> 新增设置以控制 GM_cookie 是否可以访问 HttpOnly cookies

Tempermonkey需要更新到5.3.0之后并且设置才能正确获取BDUSS
edge用户请更新到chrome商店里的版本，edge里的版本还是5.1.1

**Comment by tester00688** [comment]
> 根据Tempermonkey的更新日志
> 
> > 5.3.0
> > 2024-09-15
> > 新增设置以控制 GM_cookie 是否可以访问 HttpOnly cookies
> 
> Tempermonkey需要更新到5.3.0之后并且设置才能正确获取BDUSS edge用户请更新到chrome商店里的版本，edge里的版本还是5.1.1
> 
> 我也不知道以前怎么跑起来的
> 
> Update: 原来是1.0.9.4才加入了这个请求 [3466906](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/commit/34669060bd57ea60d72de5acd975ac3f3d93efdc)

我去看我的版本也是5.1.1 , 移除重裝才變5.3.1

但是一樣百度不能用

**Comment by Ai-Himmel** [comment]
> > 根据Tempermonkey的更新日志
> > > 5.3.0
> > > 2024-09-15
> > > 新增设置以控制 GM_cookie 是否可以访问 HttpOnly cookies
> > 
> > 
> > Tempermonkey需要更新到5.3.0之后并且设置才能正确获取BDUSS edge用户请更新到chrome商店里的版本，edge里的版本还是5.1.1
> > 我也不知道以前怎么跑起来的
> > Update: 原来是1.0.9.4才加入了这个请求 [3466906](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/commit/34669060bd57ea60d72de5acd975ac3f3d93efdc)
> 
> 我去看我的版本也是5.1.1 , 移除重裝才變5.3.1
> 
> 但是一樣百度不能用

在Tempermonkey里开启读取httpoly cookies了吗

**Comment by B0idmachine** [comment]
能用了，十分感谢

**Comment by qk-kun** [comment]
我都没法授权百度手机助手 一直提示用户未登录

**Comment by StrollStars** [comment]
> 1. 打开 “https://passport.baidu.com/accountbind” 页面，解除 “百度手机助手” 的关联
>    之后等一小段时间，等到 AccessToken 过期（时间不清楚，不过可以通过重置脚本来快速删除脚本正在使用的 AccessToken），
>    然后重新走一遍刚开始的流程……获取链接……授权脚本……获取链接……可能就能使用了

@hmjz100 依旧失败，第二点是什么意思？

@Ai-Himmel Windows 7无法升级到5.3，有其他的办法么？

**Comment by hmjz100** [comment]
大家伙，我又摸出一个新办法来了，根据现在的种种现象来看，我感觉与一个“陈年老问题”相关，以下是那个“陈年老问题”的解决方法：
1. 安装"网盘万能助手"，详情：  
Chrome 内核前往：https://www.crxsoso.com/addon/detail/mphijdmblaalbakceeadippfkbgfgaaa （原作者的插件）
FireFox 内核前往：https://addons.mozilla.org/zh-CN/firefox/addon/baidunetdiskisasb/ （热心人提供的转换后的插件）
2. 重新获取链接

如果这个方法成功了，记得回来说一声，我会抽时间给脚本加入此提示

**Comment by dao-wu-ya** [comment]
@Ai-Himmel 你的方法亲测好用，解决了无限获取问题

**Comment by Omgise** [comment]
> 大家伙，我又摸出一个新办法来了，根据现在的种种现象来看，我感觉与一个“陈年老问题”相关，以下是那个“陈年老问题”的解决方法：
> 
> 1. 安装"网盘万能助手"，详情：
>    Chrome 内核前往：https://www.crxsoso.com/addon/detail/mphijdmblaalbakceeadippfkbgfgaaa （原作者的插件）
>    FireFox 内核前往：https://addons.mozilla.org/zh-CN/firefox/addon/baidunetdiskisasb/ （热心人提供的转换后的插件）
> 2. 重新获取链接
> 
> 如果这个方法成功了，记得回来说一声，我会抽时间给脚本加入此提示

这个方法有效，不过下载“网盘网盘助手“后得先重置脚本才能正常获取链接，要不然还是一样无法获取

**Comment by Omgise** [comment]
@hmjz100 ，如果有其他解决方案就更好了，浏览器一直弹在开发者模式的通知

**Comment by hmjz100** [comment]
@Omgise 原作者有给出遇到这个提示的解决方法：
>Q：启动时弹出 [请停用以开发者模式运行的扩展程序] 怎么办？
>A：可以使用 [去除 Chrome / Edge 弹出开发者提示补丁](https://wws.lanzoub.com/b00vgnrha)，永久移除提示。[界面汉化](https://ooo.0x0.ooo/2022/05/04/zrNGX.png)

**Comment by hmjz100** [comment]
v1.0.9.6 已尝试解决该问题~ 先关闭此 issues~
