### ISSUE TITLE
189网盘下载，提示：请先登录网盘

### ISSUE THREAD

**Issue by hanxuyuan** [hmjz100/Online-disk-direct-link-download-assistant#12]
![1](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/101321354/2a98d55a-7063-4563-87ca-52b9351f4e6b)
![2](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/101321354/e61e71d9-91fd-4341-8f40-5e52acfa427f)

如图所示
明明已经登录，却一直提示登录网盘

**Comment by hmjz100** [comment]
最新版已修复
