### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by 757134** [hmjz100/Online-disk-direct-link-download-assistant#124]
小白一个，之前仅安装了Tampermonkey ，在网盘页面根本找不到下载助手按钮，脚本也没有运行。
![Tampermonkey](https://github.com/user-attachments/assets/2030a796-4a41-4c9b-899e-7d60ca1a6fcf)
之后又安装了Violentmonkey，脚本可以顺利运行。
![Violentmonkey](https://github.com/user-attachments/assets/1ef30607-5378-4f4a-873b-4ef2e5ca7f24)
不太明白为什么会产生这种差异
![combine](https://github.com/user-attachments/assets/4bd83694-70ad-4516-a3f0-6459fcab4e87)

**Comment by hmjz100** [comment]
不知道为啥，可能是因为 Tampermonkey 最近变为使用 MV3 的缘故吧
