### ISSUE TITLE
重复获取百度云盘授权

### ISSUE THREAD

**Issue by B0idmachine** [hmjz100/Online-disk-direct-link-download-assistant#130]
如题，在授权过一次后，刷新（或者不刷新）网盘界面，点击获取下载链接仍然会弹出需要获取授权的界面

**Comment by B0idmachine** [comment]
![image](https://github.com/user-attachments/assets/83de26bd-8430-4ad6-9cad-c1cab990bf78)
控制台如图

**Comment by njsink** [comment]
同样的问题，百度网盘点获取连接会一直弹出需要获取授权的界面

**Comment by hmjz100** [comment]
详情解决方案与讨论在：https://github.com/hmjz100/Online-disk-direct-link-download-assistant/issues/118#issuecomment-2412706682  
因为问题与 #118 大致一致，故此处先关闭
