### ISSUE TITLE
突然就识别到了但是更改不了网盘页了，但另外一台电脑正常；检查了edge配置并同步了也还不行

### ISSUE THREAD

**Issue by SZUKeen** [hmjz100/Online-disk-direct-link-download-assistant#131]
如图
![image](https://github.com/user-attachments/assets/c80e2575-fa01-4600-a157-c178df4b8bb0)

**Comment by SZUKeen** [comment]
试了试发现是网络代理忘记关闭了，所以一直报错；关闭代理后就正常了，不好意思(*/ω＼*)

**Comment by hmjz100** [comment]
好~ 以后记得给 unpkg.com 加个白名单哦~
