### ISSUE TITLE
阿里云盘 firefox浏览器弹出框异常

### ISSUE THREAD

**Issue by 1030504258** [hmjz100/Online-disk-direct-link-download-assistant#132]
![image](https://github.com/user-attachments/assets/48d28ba2-e73d-434f-96e4-feb91c18cc29)

**Comment by 1030504258** [comment]
chrome也异常

**Comment by 1030504258** [comment]
> 这是控制台

![image](https://github.com/user-attachments/assets/aecab5e9-86c9-409a-9154-085dac90a344)

**Comment by hmjz100** [comment]
试试这个：https://github.com/hmjz100/Online-disk-direct-link-download-assistant/issues/118#issuecomment-2415742604
