### ISSUE TITLE
新版本的edge不生效了

### ISSUE THREAD

**Issue by Xyf0606** [hmjz100/Online-disk-direct-link-download-assistant#134]
点击注入后没有显示下载按钮，且测试获取链接失败

**Comment by hmjz100** [comment]
有无 F12->控制台 报错截图

**Comment by hmjz100** [comment]
有无 F12->控制台 报错截图？

**Comment by Xyf0606** [comment]
很奇怪，今早连接vpn后反而能用了

**Comment by hmjz100** [comment]
试试在能用的情况下 打开Tampermonkey菜单，找到脚本那列 设置->服务器->不使用游小猴服务器（用jsdelivr） 看看？脚本在没访问到服务器的信息的时候是不会轻易注入按钮的，但是会有脚本菜单

**Comment by Xyf0606** [comment]
我怎么感觉是网络的问题，连vpn就没事，现在还能用，就先这样吧
