### ISSUE TITLE
直链有效期咨询

### ISSUE THREAD

**Issue by Mango-Hu** [hmjz100/Online-disk-direct-link-download-assistant#138]
我想使用这个直链生成二维码打印 所以想咨询一下直链的有效期是多久？我用的夸克网盘

**Comment by hmjz100** [comment]
直链的有效期一般很短，如果想做到二维码的直链的话我更推荐用 123 云盘（要办会员，不过应该是最值的会员了），这个网盘支持直接生成文件对应的下载直链
