### ISSUE TITLE
无法加载出“下载助手”按钮

### ISSUE THREAD

**Issue by web-lolAi** [hmjz100/Online-disk-direct-link-download-assistant#139]
夸克网盘，在Edge，油猴不管是正式版还是测试版，都加载不出来。

**Comment by hmjz100** [comment]
进油猴菜单 找改网盘直链下载助手 点击⚙设置 找使用油小猴服务器 选不使用[用 jsdelivr 连接本项目 Github 仓库]

**Comment by Lcy-NightLight** [comment]
大佬辛苦，我可能是眼睛瞎了，真找不到这个设置在哪，是油猴脚本编辑那个吗？
还是<html>
<body>
<div id="div_GihfZ2VuZXJhbA_head" class="section_head" style="vertical-align: top; font-weight: bold; font-size: 1.2em; width: 10em; padding: 20px; display: table-cell; color: rgb(0, 0, 0); font-family: Roboto, LocalRoboto, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">通用</div>
配置模式:新手初学者高级
--
语言:Browser DefaultArabic - ‎‫العربية‬‎Belarusian - беларускаяCzech - češtinaDanish - danskGerman - DeutschHellenic (Greek) - ΕλληνικάEnglishSpanish - españolFrench - françaisHindi - हिन्दीCroatian - hrvatskiHungarian - magyarIndonesian - IndonesiaItalian - italianoJapanese - 日本語Korean - 한국어Macedonian - македонскиNorwegian - norskDutch - NederlandsPolish - polskiPortuguese (Brazil) - português (Brasil)Portuguese (Portugal) - português (Portugal)Russian - русскийSlovak - slovenčinaSerbian - српскиTurkish - TürkçeUkrainian - українськаVietnamese - Tiếng ViệtChinese (Simplified) - 中文（简体中文）Chinese (Traditional) - 中文（繁體）
自动刷新页面
匿名统计数据
调试脚本
显示修正后的源码
日志记录级别:调试信息警告错误
垃圾箱模式:已启用已禁用在会话结束后清除


</body>
</html>
这个设置？

**Comment by Lcy-NightLight** [comment]
![6WZX M6H`FIAN`ZDW(PAB7D](https://github.com/user-attachments/assets/a5d0fdc4-a741-4083-a1cf-2ba24461dd95)
不知道为什么不显示设置

**Comment by hmjz100** [comment]
这……看起来像是你的网络环境不好（无法访问[`unpkg.com`](https://unpkg.com)），是我的问题……  
如果有tz的话开一下看看会不会好

**Comment by Lcy-NightLight** [comment]
> 这……看起来像是你的网络环境不好（无法访问[`unpkg.com`](https://unpkg.com)，不过我在境内用电信是能正常访问），是我的问题…… 如果有tz的话开一下看看会不会好吧

感谢作者大大，问题确定了，打不开unpkg.com这个网站，解析不到DNS服务器，我手动改了下hosts就解决这个问题了

**Comment by dabendan454** [comment]
> 进油猴菜单 找改网盘直链下载助手 点击⚙设置 找使用油小猴服务器 选不使用[用 jsdelivr 连接本项目 Github 仓库]

大佬没有“油小猴服务器”

**Comment by hmjz100** [comment]
是脚本自己的“⚙设置”而不是油猴的设置，如果找不到脚本的“⚙设置”，那请检查下网络能否访问[`unpkg.com`](https://unpkg.com/)。

**Comment by ztyanyu** [comment]
> 是脚本自己的“⚙设置”而不是油猴的设置，如果找不到脚本的“⚙设置”，那请检查下网络能否访问[`unpkg.com`](https://unpkg.com/)。

大佬辛苦，我可以直接打开[`unpkg.com`](https://unpkg.com/)，但分别在edge和google上测试了百度网盘和迅雷都加载不出来（在 油猴内打开插件 后 刷新 网盘网页 无变化），也没有在 网盘直链下载助手 的设置内找到 油小猴服务器（我大概是眼瞎了）。请问 油小猴服务器 这个选项应该会出现在 设置 里哪个位置（有截图就更好了）？又或者还可能存在什么问题导致无法显示？

**Comment by hmjz100** [comment]
![2024-11-19 18-24-9](https://github.com/user-attachments/assets/05d63da2-137f-4cb6-99e4-7c3b7f12d21a)
![2024-11-19 18-26-32](https://github.com/user-attachments/assets/adc8e6a1-9163-44fe-8c9c-77b939afcd38)

正如上图所示的“⚙设置” -> “使用油小猴服务器”

**Comment by jin-kin-l** [comment]
打开浏览器的开发者模式，重启浏览器就可以看到了

**Comment by jin-kin-l** [comment]
> > 是脚本自己的“⚙设置”而不是油猴的设置，如果找不到脚本的“⚙设置”，那请检查下网络能否访问[`unpkg.com`](https://unpkg.com/)。
> 
> 大佬辛苦，我可以直接打开[`unpkg.com`](https://unpkg.com/)，但分别在edge和google上测试了百度网盘和迅雷都加载不出来（在 油猴内打开插件 后 刷新 网盘网页 无变化），也没有在 网盘直链下载助手 的设置内找到 油小猴服务器（我大概是眼瞎了）。请问 油小猴服务器 这个选项应该会出现在 设置 里哪个位置（有截图就更好了）？又或者还可能存在什么问题导致无法显示？

打开浏览器开发者模式，重启浏览器。

**Comment by ssr123456789** [comment]
> ![2024-11-19 18-24-9](https://private-user-images.githubusercontent.com/98228280/387605462-05d63da2-137f-4cb6-99e4-7c3b7f12d21a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NTExOTAsIm5iZiI6MTczMzU1MDg5MCwicGF0aCI6Ii85ODIyODI4MC8zODc2MDU0NjItMDVkNjNkYTItMTM3Zi00Y2I2LTk5ZTQtN2MzYjdmMTJkMjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA1NTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NTg5ZDQyNTMxMzhjZTAzMGU4NTAzYWMzNWU0ZjUwNDZlMWIxMWMzMDQ1YTFlZGZhMmVhZWRkNTFmMzAzZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bQh_Fd1sMRbbQncyDHz0SzmHHgn0E5JE080RYqfS4Fc) ![2024-11-19 18-26-32](https://private-user-images.githubusercontent.com/98228280/387606508-adc8e6a1-9163-44fe-8c9c-77b939afcd38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NTExOTAsIm5iZiI6MTczMzU1MDg5MCwicGF0aCI6Ii85ODIyODI4MC8zODc2MDY1MDgtYWRjOGU2YTEtOTE2My00NGZlLThjOWMtNzdiOTM5YWZjZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA1NTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlM2QzNzM1ZGJkNjIzOTQxMDhhODM4ZmE1NmFlM2ZiMDAyMTI0OWQ2YjRiYjZjZjUyZDMxZjE3OTVkNTAwN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x8kfpzmO7sgw4oA9gmicH4WZTlWeAgvVCyY05V9vW9E)
> 
> 正如上图所示的“⚙设置” -> “使用油小猴服务器”



> 打开浏览器的开发者模式，重启浏览器就可以看到了

大佬你这个是什么浏览器

**Comment by X-Ray007** [comment]
> > 是脚本自己的“⚙设置”而不是油猴的设置，如果找不到脚本的“⚙设置”，那请检查下网络能否访问[`unpkg.com`](https://unpkg.com/)。
> 
> 大佬辛苦，我可以直接打开[`unpkg.com`](https://unpkg.com/)，但分别在edge和google上测试了百度网盘和迅雷都加载不出来（在 油猴内打开插件 后 刷新 网盘网页 无变化），也没有在 网盘直链下载助手 的设置内找到 油小猴服务器（我大概是眼瞎了）。请问 油小猴服务器 这个选项应该会出现在 设置 里哪个位置（有截图就更好了）？又或者还可能存在什么问题导致无法显示？

浏览器设置，管理扩展，找到开发者模式，打开，重启。

**Comment by qpzr** [comment]
无法访问此网站
greasyfork.org 的响应时间过长。
请试试以下办法：
检查网络连接


greasyfork.org 炸了 也一样没有下载助手

**Comment by TuanZiGit** [comment]
@hmjz100 注意到greasyfork在国内被墙了 是否考虑更换或者使用一些方式中转该文件

**Comment by TuanZiGit** [comment]
> [@hmjz100](https://github.com/hmjz100) 注意到greasyfork在国内被墙了 是否考虑更换或者使用一些方式中转该文件

比如说使用Cloudflare Workers将请求转发等（例如我修改脚本内地址为我自建的corsproxy之后正常）

**Comment by TuanZiGit** [comment]
各位 fix来了 #153 等hmjz合并 临时修复 不保证永久有效（失效后可以用魔法手段获取最新的配置导入，见pr详情）

**Comment by KleinAsyourwish** [comment]
把旧版1.0.9.6删了，换成linkswift1.0.9.7，下载助手出现了。
大佬，更新为什么直接改掉插件名字啊

**Comment by chongli117** [comment]
> 这……看起来像是你的网络环境不好（无法访问[`unpkg.com`](https://unpkg.com)，不过我在境内用电信是能正常访问），是我的问题…… 如果有tz的话开一下看看会不会好吧

我可以访问这个，我在手机端的Kiwi浏览器，分明打开了扩展的开发者模式，但是浏览器总提示我打开是怎么回事？

![Image](https://github.com/user-attachments/assets/f1bf5803-b6c4-4d3a-9da0-b7dc8ed39477)

![Image](https://github.com/user-attachments/assets/34ae4fc1-1ce2-462f-83b9-79a088391b8d)

并且我和这个提问者一样，安卓手机在kiwi浏览器进入网页版百度网盘、夸克网盘，都看不显示插件。

![Image](https://github.com/user-attachments/assets/e92486fa-4423-4ab3-a365-aec1dfa3703e)

**Comment by z-zn-nh** [comment]
网页端不显示下载助手，不知道是不是被ban了

<img width="1999" height="189" alt="Image" src="https://github.com/user-attachments/assets/58e72920-dba1-4bb5-bde2-719bc0d6aa1d" />

**Comment by TuanZiGit** [comment]
> 网页端不显示下载助手，不知道是不是被ban了
> 
> <img alt="Image" width="1999" height="189" src="https://private-user-images.githubusercontent.com/214328481/468352171-58e72920-dba1-4bb5-bde2-719bc0d6aa1d.png">

<img width="1087" height="196" alt="Image" src="https://github.com/user-attachments/assets/1bf7b832-f8f7-4c88-a620-24098e91fc73" />

没问题啊

**Comment by Mind-Island** [comment]
同样，但我换老版本谷歌配旧版本油候或者别的浏览器都能显示，就最新版谷歌配最新油候不行，我猜是谷歌的锅？

**Comment by toss-a** [comment]
> 同样，但我换老版本谷歌配旧版本油候或者别的浏览器都能显示，就最新版谷歌配最新油候不行，我猜是谷歌的锅？

在最新的谷歌浏览器上似乎对浏览器插件进行了权限管理，我测试在新新油候测试版本中开启这些功能即可启用

<img width="812" height="1191" alt="Image" src="https://github.com/user-attachments/assets/6afd2685-17b6-417e-a904-4a5174f5a579" />

**Comment by FredPan04** [comment]
就是谷歌的锅，需要打开油猴下面的允许运行用户脚本

**Comment by jafox-12** [comment]
你好，我打开了“开发者模式”，能进入unpkg，但是脚本自己的“设置”按钮还是没有

<img width="307" height="173" alt="Image" src="https://github.com/user-attachments/assets/2af37232-6f60-4944-bf2b-9cf92a259ba5" />

<img width="1199" height="619" alt="Image" src="https://github.com/user-attachments/assets/01ffc2b5-7da1-4c15-b317-9926cbdffec8" />
<img width="202" height="71" alt="Image" src="https://github.com/user-attachments/assets/f1dd9cea-b869-4d87-b6ce-71f26f8ac107" />
