### ISSUE TITLE
网盘不显示解析按钮

### ISSUE THREAD

**Issue by Lcy-NightLight** [hmjz100/Online-disk-direct-link-download-assistant#140]
百度网盘和夸克网盘(仅测试这两个)均不显示解析按钮，无法获取直链
环境1 脚本版本1.0.9.6
插件版本Tampermonkey BETA v5.3.6216
浏览器版本EDGE 124.0.2478.97 (正式版本) (64 位)
环境2 脚本版本1.0.9.6
插件版本Tampermonkey BETA v5.1.6194
浏览器版本 (Chromium 86.0.4240.198)

**Comment by hmjz100** [comment]
与 #139 相同

**Comment by TuanZiGit** [comment]
已修复 见 #153 临时修复不保证永久有效
