### ISSUE TITLE
idm bug

### ISSUE THREAD

**Issue by Tisure** [hmjz100/Online-disk-direct-link-download-assistant#142]
idm下载很慢咋办？？？

> 
![屏幕截图 2024-11-18 213913](https://github.com/user-attachments/assets/22bc4d22-3fb4-4bbf-bbf5-17606a7cd5dd)

**Comment by hmjz100** [comment]
没有咋办，也不是 Bug，脚本本来就不是破解下载加速，只是获取文件对应的下载链接罢了

**Comment by wanghe1358** [comment]
开会员

**Comment by FlootingDream** [comment]
> 开会员

有会员也很慢

**Comment by FlootingDream** [comment]
> 没有咋办，也不是 Bug，脚本本来就不是破解下载加速，只是获取文件对应的下载链接罢了

有会员也很慢

**Comment by love2B** [comment]
win11，用新油猴，红色的那个。在edge中打开百度网盘，点击文件上的下载助手。在上方弹出一个连接后。迅速打开了一个新页面。然后就不让下载了。新页面是openapi.baidu.com ，提示关闭了什么 东西。我换回旧版本油猴正常使用但是无法打开idm。其实这个还好。

**Comment by Cc729091099** [comment]
> 没有咋办，也不是 Bug，脚本本来就不是破解下载加速，只是获取文件对应的下载链接罢了

![Image](https://github.com/user-attachments/assets/d2f5f4eb-3d17-4780-b96e-ef1971fce67f)速度怎么这么慢呀？那个百度网盘会员脚本也安装了。只能提取下载链接，不能加速吗？

**Comment by wu-kang66** [comment]
如果速度很慢的话，还不如用客户端下
