### ISSUE TITLE
idm线程少，建议优化

### ISSUE THREAD

**Issue by one-ccluo** [hmjz100/Online-disk-direct-link-download-assistant#147]
idm下载线程才几条，速度1m多每秒
![1733298565303](https://github.com/user-attachments/assets/61d299bf-f1f8-4409-bd99-90a9c40c8036)

**Comment by hmjz100** [comment]
这是网盘的限制，获取到的链接均为网盘官方下载源，源头做的限制脚本怎么都不可能“优化”
