### ISSUE TITLE
能识别，但是不显示下载助手那个按钮，重新安装也没用

### ISSUE THREAD

**Issue by Jasonanywhere** [hmjz100/Online-disk-direct-link-download-assistant#2]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/88193248/193232806-def6b92c-d038-41c6-b607-6c4202fc24b8.png">

**Comment by hmjz100** [comment]
等会，我先注册一个夸克号

**Comment by hmjz100** [comment]
修好了，去**Greasy Fork**更新看看能不能解决，如果不能，我再改改。

**Comment by Jasonanywhere** [comment]
能用了，还改了字体颜色，看着舒服了

**Comment by hmjz100** [comment]
好的👌，如果您有新问题可以再建立一个issue，这个issue我就关闭了，也感谢您帮助我找到了bug！

**Comment by hmjz100** [comment]
好的👌，如果您有新问题可以再建立一个issue，这个issue我就关闭了，也感谢您帮助我找到了bug！
