### ISSUE TITLE
百度和阿里盘都找不到直链助手的按钮啊！！！重装+刷新都木有！！！

### ISSUE THREAD

**Issue by kakushou** [hmjz100/Online-disk-direct-link-download-assistant#20]
网盘页面上压根找不到直链助手的按钮啊！！！ 重装+刷新都试了还是木有！！！是失效了吗？？？ 盼fix

**Comment by hmjz100** [comment]
因为我没有复现成功您说的问题，但是最近好多人都说不显示按钮。
为了方便我分析，请您打开有问题的页面，然后按下F12打开浏览器开发控制台并切换到“控制台/Console”选项卡，之后复制带有“userscript”字样的报错提示（有多条报错的话也要复制哦），最后发给我分析就好啦（我会尽快更新的！）

**Comment by ming554** [comment]
网络问题

**Comment by kakushou** [comment]
> 因为我没有复现成功您说的问题，但是最近好多人都说不显示按钮。 为了方便我分析，请您打开有问题的页面，然后按下F12打开浏览器开发控制台并切换到“控制台/Console”选项卡，之后复制带有“userscript”字样的报错提示（有多条报错的话也要复制哦），最后发给我分析就好啦（我会尽快更新的！）

截了几张图  怎么发给你？？？  留个邮箱

**Comment by hmjz100** [comment]
新版本已修复，请进入油猴菜单中的“⚙ 设置”→找到“使用油小猴服务器”→选择“不使用（使用GhProxy连接Github仓库获取信息,更新可能不及时）”可能会解决该情况。

**Comment by kakushou** [comment]
按鈕回來了  THX

**Comment by Kyle1st** [comment]
油猴菜单中的“⚙ 设置”在哪里啊 找不到

**Comment by hmjz100** [comment]
@Kyle1st 检查您是否已经打开了网盘页面，以及检查网络是否能够访问 `https://unpkg.com`
