### ISSUE TITLE
v1.7.0.4，阿里云盘分享发送到RPC下载，会同时出现2个任务。

### ISSUE THREAD

**Issue by Azreulo** [hmjz100/Online-disk-direct-link-download-assistant#23]
如图：勾选了一个文件。
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/21158437/11f54075-97fd-4333-9692-ef6b0f34f571)

推送到RPC后，出现两个任务。
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/21158437/b20c0b4f-b492-4e03-9776-f5346d54d76d)

**Comment by Ziyueqi-V** [comment]
是的，有的时候不止出现两个，选中多个文件时，每个文件都会被重复添加两三个下载任务

**Comment by hmjz100** [comment]
v1.0.7.5已修复，请安装新版本。
