### ISSUE TITLE
已使用Tampermonkey, 但无法获取链接

### ISSUE THREAD

**Issue by BeastSenpai1919810** [hmjz100/Online-disk-direct-link-download-assistant#25]
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/121651381/47285eff-648c-43b1-9cd8-5dc70c05b29d)
如图所示
我目前已经使用红色的油猴, 此种情况主要出现在百度网盘. (无会员)
天翼云网盘能够正常使用.

**Comment by hmjz100** [comment]
V1.0.7.8已修复，建议删除脚本然后重装再配置
