### ISSUE TITLE
推送到AriaNg，无法创建任务，请教大佬是何原因。。。

### ISSUE THREAD

**Issue by drw2005** [hmjz100/Online-disk-direct-link-download-assistant#27]
当前RPC测试成功，但是RPC下载里的发送全部链接到Aria2，却没有看到任何下载任务，好像推送没成功。
请教是哪里问题？
![QQ截图20230921094340](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/33473981/f96aa75b-78cf-4c87-b507-db3cae0d40d3)

![00000000000000000000000](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/33473981/2931f167-858a-4cce-ae17-48a7310ab38e)

PS：刚才又试了一下，百度网盘推送不成功，但是阿里网盘能推送成功，但是一次推送了两个下载任务。
用的最新版本1.0.7.8

**Comment by hmjz100** [comment]
我也不知道它为啥一次就会创建这么多的重复任务，不过之后会尝试解决。
一般程序访问C盘（指系统盘）都需要管理员权限，所以请检查一下你的Aria2有没有以管理员身份运行。
