### ISSUE TITLE
您好，插件无法唤醒IDM

### ISSUE THREAD

**Issue by zhangyang924** [hmjz100/Online-disk-direct-link-download-assistant#28]
IDM已经注册，但是网盘下载的话，无法唤醒IDM
<img width="1796" alt="屏幕截图_20230923_222805" src="https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/76587247/dc97ca71-5e0b-445a-9089-7c4133bd8fe4">

**Comment by zhangyang924** [comment]
求助求助，大佬知道怎么回事嘛？

**Comment by hmjz100** [comment]
是正版/盗版IDM的话请检查IDM里有没有添加PDF的名称，或者检查盗版IDM的扩展是不是破解版，
我使用的IDM是某23down的6.41 Build2 (2022年5月31号) 版，链接可以正常被捕获。
IDM捕获原理为通过扩展拦截浏览器下载请求，并且给浏览器返回一条链接已被IDM拦截的消息，脚本检测到这条返回的消息就会提示被IDM捕获并停止下载。

**Comment by fatfattree** [comment]
同样不能唤起IDM，只能浏览器下载，IDM版本是6.41 build18，但用原版下载助手就可以正常唤起。扩展名那些都是常用文件，都有添加的。大佬看看是什么情况？
