### ISSUE TITLE
阿里云盘，API下载，无法弹出提示的“浏览器下载框”

### ISSUE THREAD

**Issue by Gungnir762** [hmjz100/Online-disk-direct-link-download-assistant#29]
在文件进度条下载完后一直没有任何提示框弹出，点击“下载全部链接”也不会重新弹出保存提示。
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/83220033/cadcb394-1013-49af-afb1-7809f3761cc0)
注：已经按照说明文档取消了本机的IDM对阿里云相关的三个域名的接管，在chrome和edge最新版下均无法保存文件到本地

**Comment by Gungnir762** [comment]
另外，在windows powershell下使用curl会报错：`curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 吊销功能无法检查证书是否吊销。`
Linux Shell可以正常使用curl

**Comment by Stanley-baby** [comment]
我也遇到了这个问题，请问有解决办法吗？

**Comment by Gungnir762** [comment]
> 我也遇到了这个问题，请问有解决办法吗？

使用linux shell()
