### ISSUE TITLE
已安装1.0.78版本，重新安装了几次脚本，Aria2还是下载不了

### ISSUE THREAD

**Issue by OOZYUAN** [hmjz100/Online-disk-direct-link-download-assistant#31]
<img width="821" alt="e258838e12c9589732177f253ff497f" src="https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/147244309/d80c228b-6d09-4183-ab65-7db8aea7a665">

**Comment by hmjz100** [comment]
看样子您应该装了其他的“网盘直链下载助手”，请卸载其他版本后再试
