### ISSUE TITLE
一直显示获取链接失败，退出登录也没有用T_T

### ISSUE THREAD

**Issue by zhizunjiaopi** [hmjz100/Online-disk-direct-link-download-assistant#32]

**Comment by hmjz100** [comment]
去 https://openapi.baidu.com/oauth/2.0/authorize?client_id=IlLqBbU3GjQ0t46TRwFateTprHWl39zF&response_type=token&redirect_uri=oob&scope=basic,netdisk 授权，成功后页面显示“百度OAuth2.0”应该就可以获取了
