### ISSUE TITLE
阿里云盘选择 api 下载后，浏览器不弹出窗。

### ISSUE THREAD

**Issue by Stanley-baby** [hmjz100/Online-disk-direct-link-download-assistant#33]
阿里云盘选择 api 然后点击链接下载后，下载完成后浏览器的下载窗口不弹出，并且找不到下载完的文件。

**Comment by hmjz100** [comment]
那就奇怪了，我的百分浏览器是可以正常弹出的，检查下浏览器有没有提示说“XXX想要下载多个文件”之类的提示，如果有就允许

**Comment by Stanley-baby** [comment]
没有弹窗，只下载一个文件也一样，目前只有阿里云盘是这样，百度云下载完成后就会在浏览器中弹出。

**Comment by Stanley-baby** [comment]
对了   还有一个   在 Safari 上不起效果  没有显示按钮
