### ISSUE TITLE
已勾选文件，但一直提示“请先勾选要下载的文件捏~”

### ISSUE THREAD

**Issue by xiongpahao** [hmjz100/Online-disk-direct-link-download-assistant#34]
如题，迅雷网盘。使用的是Tampermonkey Beta的最新版。具体可见附件视频。

https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/12950426/f7fa2c22-b2e1-4eaf-ad13-3ce0ea6dc0b2

**Comment by hmjz100** [comment]
再等等吧，请去[原脚本反馈区](https://greasyfork.org/scripts/436446/feedback)那儿反馈，因为我目前还没摸索到解决方案

**Comment by forthepeak** [comment]
> 再等等吧，请去[原脚本反馈区](https://greasyfork.org/scripts/436446/feedback)那儿反馈，因为我目前还没摸索到解决方案

大佬大佬，有位叫r4p0的大佬在原脚本反馈区里提出解决方案了，我改了后选中问题解决了，您可以去看看。[跳转链接在这](https://github.com/syhyz1990/baiduyun/issues/269#issuecomment-1793517923)

**Comment by xiongpahao** [comment]
感谢感谢！确实解决了问题！！！> > 再等等吧，请去[原脚本反馈区](https://greasyfork.org/scripts/436446/feedback)那儿反馈，因为我目前还没摸索到解决方案
> 
> 
> 
> 大佬大佬，有位叫r4p0的大佬在原脚本反馈区里提出解决方案了，我改了后选中问题解决了，您可以去看看。[跳转链接在这](https://github.com/syhyz1990/baiduyun/issues/269#issuecomment-1793517923)

**Comment by hmjz100** [comment]
> > 再等等吧，请去[原脚本反馈区](https://greasyfork.org/scripts/436446/feedback)那儿反馈，因为我目前还没摸索到解决方案
> 
> 大佬大佬，有位叫r4p0的大佬在原脚本反馈区里提出解决方案了，我改了后选中问题解决了，您可以去看看。[跳转链接在这](https://githubfast.com/syhyz1990/baiduyun/issues/269#issuecomment-1793517923)

感谢帮助，V1.0.8已修复（已经修改过代码的别忘了把脚本```设置→更新→检查更新```勾选上哦）
