### ISSUE TITLE
请求修复适配X浏览器、可拓浏览器等安卓浏览器

### ISSUE THREAD

**Issue by Winnie-Teh-Pooh** [hmjz100/Online-disk-direct-link-download-assistant#35]
①可拓浏览器，下拉菜单位置错位，无法使用（点击一次下载助手，会自动使用和按钮位置重合起来的Aria，就无法使用其他功能了）
![Uploading IMG_20231106_113214.jpg…]()

②X浏览器使用“下载助手”下拉菜单的功能时一直转圈圈，无法正常使用
![Uploading Screenshot_2023-11-06-11-34-30-88_e5a83ae45535e2dd2464ee4feacee5c7.jpg…]()

**Comment by Winnie-Teh-Pooh** [comment]
![Uploading IMG_20231106_113214.jpg…]()

**Comment by hmjz100** [comment]
你传的图片我这边全部加载不出来欸，不过照你的描述的话我建议换个浏览器，  
比如“狐猴浏览器”“Kivi浏览器”这两个支持直接安装扩展而且经过测试能成功下载的浏览器
