### ISSUE TITLE
ios系统 safari浏览器支持问题。

### ISSUE THREAD

**Issue by SSrFreak** [hmjz100/Online-disk-direct-link-download-assistant#36]
用的是ipad，然后油猴插件使用stay进行脚本管理的，最关键是百度网盘下载助手、以及设置地址、端口、路径都能成功设置，最后点具体下载文件，使用RPC的时候，一直显示获取链接转圈，但是不弹显示发送详情的小窗；这个改版的也用了，原版的网盘直链下载助手也用了，都是这个问题，就是小窗弹不出来，能不能解决下，ios系统不能用这个很难受。

**Comment by hmjz100** [comment]
我没有Safari浏览器或者IOS，不过你可以试试打开  
[https://openapi.baidu.com/oauth/2.0/authorize?client_id=IlLqBbU3GjQ0t46TRwFateTprHWl39zF&response_type=token&redirect_uri=oob&scope=basic,netdisk](https://openapi.baidu.com/oauth/2.0/authorize?client_id=IlLqBbU3GjQ0t46TRwFateTprHWl39zF&response_type=token&redirect_uri=oob&scope=basic,netdisk)  
进行授权（成功后会显示“百度OAuth2.0”）之后再试试获取吧

**Comment by SSrFreak** [comment]
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/143402067/52d586ea-941e-462c-9f31-6fb012633129)


一直卡在这个地方。

**Comment by zirawell** [comment]
同样的问题，Mac用stay加载这个脚本在Safari无法获取链接，Chrome可以用油猴获取到链接
