### ISSUE TITLE
下载时，虽然勾选了，但是总是提示“请先勾选要下载的文件捏~”，无下载对话框

### ISSUE THREAD

**Issue by a563924028** [hmjz100/Online-disk-direct-link-download-assistant#37]
![请先勾选要下载的文件捏~](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/85891813/83adc55c-4e1f-4063-b940-8f145836b310)

**Comment by a563924028** [comment]
使用油小猴服务器设置里，V1 V2 不使用，均试了试设置，都没有解决

**Comment by a563924028** [comment]
前些天貌似有两天修复了这个问题，也成功在迅雷网盘里运行下载，目前这两天（11月12日）又不行了。是迅雷做了限制了？

**Comment by hmjz100** [comment]
V1.0.8.1已修复
