### ISSUE TITLE
按钮消失

### ISSUE THREAD

**Issue by seien210300928** [hmjz100/Online-disk-direct-link-download-assistant#40]
![QQ图片20231120235505](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/68688963/c1f21a8a-e81e-423d-bf74-24128a104b77)

**Comment by LOVE2CMOL** [comment]
原作者地址挂了 
挂梯子
使用GhProxy连接Github仓库获取信息

**Comment by kokd2001** [comment]
其他網盤正常,但是阿里雲按鈕消失

**Comment by SolomonLeon** [comment]
@LOVE2CMOL ghproxy的配置在svip网盘上无法获取文件，请问你有遇到过这样的问题吗

**Comment by hmjz100** [comment]
这是原作者服务器出问题了  
不过现在我已经可以正常访问原作者服务器了，故关闭本议题。
