### ISSUE TITLE
在已经安装了红猴的情况下，在推送任务的时候继续提示更换为更强大的红猴

### ISSUE THREAD

**Issue by leyouleo** [hmjz100/Online-disk-direct-link-download-assistant#43]
主要问题已经在标题了，不知道是那一步出了错

**Comment by hmjz100** [comment]
试试去[https://openapi.baidu.com/oauth/2.0/authorize?client_id=IlLqBbU3GjQ0t46TRwFateTprHWl39zF&response_type=token&redirect_uri=oob&scope=basic,netdisk](https://openapi.baidu.com/oauth/2.0/authorize?client_id=IlLqBbU3GjQ0t46TRwFateTprHWl39zF&response_type=token&redirect_uri=oob&scope=basic,netdisk)做授权，完成之后会显示百度Oauth2.0

**Comment by psbo** [comment]
您遇到了错误！
错误代码：referer_mismatch
错误信息：Invalid Referer
详细描述：当前页面的Referer错误。[使用Implicit Grant方式获取Access Token时](http://developer.baidu.com/wiki/index.php?title=docs/oauth/implicit)，Referer必须与应用的根域名绑定同域，请在开发者在应用安全设置中进行绑定。
