### ISSUE TITLE
兄啊，最近一直弹出「提示：获取下载链接失败！请刷新网页后重试！」无法下载力

### ISSUE THREAD

**Issue by ChexMauDu** [hmjz100/Online-disk-direct-link-download-assistant#6]
RT.
![1671274565847](https://user-images.githubusercontent.com/86345628/208238364-f585ae35-09f7-4a36-913d-ad8c36b5eedd.jpg)

**Comment by ChexMauDu** [comment]
现在又能用了，不知道是哪里的问题。

**Comment by hmjz100** [comment]
可能是原作者服务器崩了一会儿吧，没事我就结束这个Issues了
