### ISSUE TITLE
迅雷云盘失效，选择文件依然提示选择

### ISSUE THREAD

**Issue by byzod** [hmjz100/Online-disk-direct-link-download-assistant#62]
控制台无错误或警告输出
![Snipaste_2024-02-27_19-18-49](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/848607/6517a96f-b130-4dfe-8914-113d00db96d9)

**Comment by byzod** [comment]
1.0.8.3
firefox

**Comment by hmjz100** [comment]
v1.0.8.7 未发现该问题，建议更换“油小猴服务器”为V2
