### ISSUE TITLE
阿里盘点击没有反应，一直显示未点亮在那闪

### ISSUE THREAD

**Issue by freedomspiritJohn** [hmjz100/Online-disk-direct-link-download-assistant#63]

**Comment by 3320099** [comment]
一样的路过

**Comment by tcstory** [comment]
+1

**Comment by toutou6366** [comment]
一直显示未点亮，也不说明怎么操作

**Comment by wenwen12345** [comment]
https://www.aliyundrive.com/drive/file/backup
打开这个界面点击那个按钮，点注入点亮，就行了

**Comment by tcstory** [comment]
> https://www.aliyundrive.com/drive/file/backup 打开这个界面点击那个按钮，点注入点亮，就行了

这个方法有效. 不过我想知道, 是不是现在在阿里网盘下载东西, 必须要先保存到自己的网盘中? 因为我在别人的界面那里, 根本看不到下载工具的按钮

**Comment by hmjz100** [comment]
v1.0.8.7 已修复
