### ISSUE TITLE
明明已經安裝 紅色BETA版 卻仍然出現提示

### ISSUE THREAD

**Issue by bluelovers** [hmjz100/Online-disk-direct-link-download-assistant#69]
明明已經安裝 紅色BETA版 卻仍然出現提示
並且已經禁用黑色普通版

![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/167966/715457ca-377c-4d1b-9777-2686f631a92c)

**Comment by hmjz100** [comment]
v1.0.8.7 未发现该问题，首先试试重新登录网盘，然后安装辅助脚本[网盘万能助手 (来源:原作者的插件站)](https://www.crxsoso.com/addon/detail/mphijdmblaalbakceeadippfkbgfgaaa)，安装完成后刷新页面即可
