### ISSUE TITLE
请问大家现在怎么下载阿里云盘的文件?

### ISSUE THREAD

**Issue by YJL12345** [hmjz100/Online-disk-direct-link-download-assistant#70]
脚本失效了,拿不到链接,不想下载客户端,只有网页怎么办

**Comment by sanbei011** [comment]
脚本失效了吗!

**Comment by tcstory** [comment]
恩,  遇到同样的问题了

**Comment by mottzz87** [comment]
第2939行增加一句代码就可以了
base.setValue('setting_youxiaohou_server', 'no')
![Uploading image.png…]()

**Comment by YJL12345** [comment]
这个脚本不能通过别人的分享链接拿下载链接的吗?只能在自己的网盘里面又下载按钮

**Comment by tcstory** [comment]
> base.setValue('setting_youxiaohou_server', 'no')

也许是版本不一样? 我并没有看到 2939 这一行. 最多只有 2849 行, 版本是6.1.6

**Comment by tcstory** [comment]
不懂怎么搞了,   重新安装后, 连下载按钮都看不到了

**Comment by Jiangdonganxia** [comment]
> 第2939行增加一句代码就可以了 base.setValue('setting_youxiaohou_server', 'no')

大佬，有什么内幕消息吗，现在连不上服务器

**Comment by hmjz100** [comment]
v1.0.8.7 未发现该问题，原作者服务器也可访问了，建议更换“油小猴服务器”为V2
