### ISSUE TITLE
macOS  RPC推送到Motrix 之后自动停止

### ISSUE THREAD

**Issue by AirTouch666** [hmjz100/Online-disk-direct-link-download-assistant#71]
macOS  RPC推送到Motrix 之后自动停止
放到“已停止”里面，有的还显示下载 100%，但下载文件夹里没有

**Comment by hmjz100** [comment]
v1.0.8.7 未发现该问题，建议更换Mortix的下载UA的选项为du，没有du的话UA就换为`netdisk;6.0.0.12;PC;PC-Windows;10.0.16299;WindowsBaiduYunGuanJia`
