### ISSUE TITLE
迅雷网盘再次出现无法识别已勾选文件问题

### ISSUE THREAD

**Issue by Fe4FeCN63** [hmjz100/Online-disk-direct-link-download-assistant#72]
勾选文件后尝试使用RPC下载，提示未勾选文件
<img width="1280" alt="屏幕截图 2024-03-24 112318" src="https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/150653319/79bdb2dd-0a4b-44c6-99c0-69cea0640233">

**Comment by hmjz100** [comment]
v1.0.8.7 未发现该问题，建议更换“油小猴服务器”为V2
