### ISSUE TITLE
idm下载bug

### ISSUE THREAD

**Issue by LLdandelion** [hmjz100/Online-disk-direct-link-download-assistant#73]
百度网盘使用api下载后点击“下载全部连接”或者单个点击文件会出现多次重复弹窗
求大佬救救，
<img width="597" alt="屏幕截图 2024-03-31 085843" src="https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/143794634/9ac44a44-0cad-4586-a2ac-7750e77f6dbe">
谢谢大佬维护脚本

**Comment by hmjz100** [comment]
V1.0.8.4 已修复
