### ISSUE TITLE
阿里云盘

### ISSUE THREAD

**Issue by luojeff23** [hmjz100/Online-disk-direct-link-download-assistant#76]
我这有个按键是未点亮咋回事呢，而且配置了rpc还是发送失败呜呜呜
![截图](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/122669722/72868da0-93bc-4f75-98a6-3bf1304e8a0d)

**Comment by Jiangdonganxia** [comment]
点完测试就这样了

**Comment by Jiangdonganxia** [comment]
我是在自己网盘首页刷新弹出了重新输入暗号就行了，但下载还是不能下载东西

**Comment by hmjz100** [comment]
v1.0.8.7 已修复
