### ISSUE TITLE
阿里云盘无法使用

### ISSUE THREAD

**Issue by xinconan** [hmjz100/Online-disk-direct-link-download-assistant#80]
选择API下载，进度为0，控制台报错了。
injected: Refused to connect to "": Blocked by @connect CORS check

**Comment by hmjz100** [comment]
阿里云盘现在貌似不支持在分享页面下载了，转存到自己网盘在下吧

**Comment by tcstory** [comment]
好像不会了, 我试过了, 确认你安装的是 1.0.8.8

**Comment by tcstory** [comment]
> 阿里云盘现在貌似不支持在分享页面下载了，转存到自己网盘再下吧

刚刚试了一下, 好像不需要哦

**Comment by xinconan** [comment]
> 好像不会了, 我试过了, 确认你安装的是 1.0.8.8

是这个版本，谷歌和edge都试了，一样的错，不知道是不是我容量满了的原因

**Comment by kkjj116** [comment]
阿里云盘用API下载，下载完了提示浏览器弹出窗口，结果啥都不弹，用的chrome

**Comment by fengyewqsk** [comment]
阿里云盘5月28日目前所有都无法使用

**Comment by LeviMarvin** [comment]
阿里云盘现在下载要验证特定请求字段来鉴权`x-oss-signature-version`，Query string authentication x-oss-signature-version is invalid.

**Comment by LeviMarvin** [comment]
原因是阿里云盘用阿里云的OSS存储，阿里云的OSS存储需要鉴权访问

**Comment by LeviMarvin** [comment]
可以通过curl命令添加`-k`忽略证书校验，阿里云似乎启用了内部非公开信任的证书来传输数据

**Comment by hmjz100** [comment]
现在似乎没有这个问题了，此问题时间过长，且无法复现，先暂时关闭
