### ISSUE TITLE
脚本失效

### ISSUE THREAD

**Issue by Omgise** [hmjz100/Online-disk-direct-link-download-assistant#83]

**Comment by Omgise** [comment]
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/106000018/96af3a7d-44a2-4398-8a94-2b8456da2ec6)
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/106000018/42b9556e-31fd-49c5-aea6-41643b4e6d98)
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/106000018/3bfe5476-6483-49cf-a8a5-71a5bc9719c3)

**Comment by Enhe12138** [comment]
同样的问题 同样的报错，有解决办法麻烦踢我一下，谢谢

**Comment by hmjz100** [comment]
出大问题了，原脚本以及此脚本和别的同类型脚本在 Greasy Fork 被丛林寻宝儿儿这个🤡举报了，这是那个🤡曾经举报此脚本时不小心暴露出的网盘文件的截图  
![0ifahsviy5d5yuf3jfnl76qeeoz7](https://greasyfork.s3.us-east-2.amazonaws.com/0ifahsviy5d5yuf3jfnl76qeeoz7)  
而且现在不能使用是因为原脚本被举报导致此脚本不能获取到原脚本的版本信息，而原作者的接口又必须要这些信息，且[目前 Greasy Fork 的常任管理员](https://greasyfork.org/moderator_actions)跟我们有时差，现在不能受理那个🤡的举报  
各位可以去 [Greasy Fork 的仓库](https://github.com/greasyfork-org/greasyfork) 发个issues跟管理员提下此脚本和别的同类型脚本被讨论区乱差评和乱举报的事，这样大家也能及时恢复使用此脚本

**Comment by hmjz100** [comment]
目前的解决方法仅针对之前已经正常安装过脚本且已点亮按钮的用户：
1. 编辑脚本：搜索到此脚本的 `await base.fetchScriptInfo('https://greasyfork.org/zh-CN/scripts/436446.json` 这一行代码，并且将其整块内容注释掉 此时那部分代码将变为
```
/*await base.fetchScriptInfo('https://greasyfork.org/zh-CN/scripts/436446.json', 5).then(res => {
	base.setValue('setting_script_version', res.version);
	base.setValue('setting_script_author', 'GreasyFork');
	base.setValue('setting_script_name', res.name);
})*/
```
2. 保存，并且刷新网页即可重新显示按钮

**Comment by Omgise** [comment]
谢谢，这个方法有效！

**Comment by AriesVayne** [comment]
> ![image](https://private-user-images.githubusercontent.com/106000018/330673379-96af3a7d-44a2-4398-8a94-2b8456da2ec6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjM2ODEsIm5iZiI6MTcxNjI2MzM4MSwicGF0aCI6Ii8xMDYwMDAwMTgvMzMwNjczMzc5LTk2YWYzYTdkLTQ0YTItNDM5OC04YTk0LTJiODQ1NmRhMmVjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwMzQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzNjMjVjOTE4NDMwYzQ2YzYyYzRkN2U0MDgyNTgzNTAzZGNhOGViNzMxZTVkZDIxMzYzNGM0ZTIwZjcyZmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H9HyeZ-cc7WBdLxed9jlA9n-pLs9EvR4UYjv1uXC6sY) ![image](https://private-user-images.githubusercontent.com/106000018/330673384-42b9556e-31fd-49c5-aea6-41643b4e6d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjM2ODEsIm5iZiI6MTcxNjI2MzM4MSwicGF0aCI6Ii8xMDYwMDAwMTgvMzMwNjczMzg0LTQyYjk1NTZlLTMxZmQtNDljNS1hZWE2LTQxNjQzYjRlNmQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwMzQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzg4YzFiYjgwZTJjOGQ3MGI3Y2ViNmU2M2MzYTIzYzU4NTY0Y2NmZTU3YTUyYjFlMDU4MzAxNTg0OGYxY2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vQ0CmR95uJxD4koQjlSLCozdlwEij9hQMLvK-aJY8lI)

咋回事啊,又不能用了?

**Comment by Omgise** [comment]
现在脚本已经可以正常使用了
