### ISSUE TITLE
百度云盘无法使用

### ISSUE THREAD

**Issue by oliveoil212** [hmjz100/Online-disk-direct-link-download-assistant#87]
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/55798323/7912415a-46d8-4a13-9e52-76a6ed5fcca9)

**Comment by hmjz100** [comment]
安装下原作者的RPC辅助插件试试，帮助脚本获取BDUSS，地址是原作者的插件站:https://www.crxsoso.com/addon/detail/mphijdmblaalbakceeadippfkbgfgaaa

**Comment by lanyoooo** [comment]
我也是，从百度云盘点击API下载就提示无法获取链接，错误代码9019
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/104418803/f65efcdd-12fe-4e43-ae70-61c729ea5a5c)

**Comment by BrunoTwelve** [comment]
+1，跟楼上一样，获取不了链接，代码9019

**Comment by henryyifan** [comment]
+1，跟楼上一样，获取不了链接，代码9019

**Comment by ningyuwhut** [comment]
+1, 代码9019

**Comment by blblkang** [comment]
> 安装下原作者的辅助插件试试，帮助脚本获取BDUSS，地址是原作者的插件站：https://www.crxsoso.com/addon/detail/mphijdmblaalbakceeadippfkbgfgaaa

安装插件后依然不可用，代码9019

**Comment by tafeilgh** [comment]
+1, 代码9019

**Comment by AnyoeDove** [comment]
9013/9019是账户被封禁的提示.....建议短期内不要使用了

**Comment by henryyifan** [comment]
> 9013/9019是账户被封禁的提示.....建议短期内不要使用了....
> 
> 解除封禁方法：修改密码 在百度云盘app在线咨询客服那里发“已完成密码修改申请解封账号”

可是我的并没有封禁啊，账号一切正常，还是9019，换了另一个账号也是如此

**Comment by Loss-of-time** [comment]
+1
全新账号依然9019

**Comment by Giresharu** [comment]
应该是解析服务被 ban 了，大约是 gg 了

**Comment by Loss-of-time** [comment]
> 应该是解析服务被 ban 了，大约是 gg 了

😭

**Comment by mzji** [comment]
同 9019 ，感觉需要重新搞解析逻辑了

**Comment by jmlevol** [comment]
亲测还能用，应该是chrome的原因，在chrome上清完数据换号都试过不行，但是换成edge就可以了

**Comment by henryyifan** [comment]
现在网页版的按钮也消失了

**Comment by blblkang** [comment]
> 现在网页版的按钮也消失了

这个似乎一直都有，时不时就没有按钮一下

**Comment by LaelLuo** [comment]
很简单的原因 解析逻辑用的百度开发者api弄的
https://github.com/hmjz100/Online-disk-direct-link-download-assistant/blob/b008fa368fbf8af30b46a69404e7bb0444261c4c/config/config.json#L8
估计这个申请的应用直接被百度删了 所以解析不了了

**Comment by Rnreck** [comment]
> 很简单的原因 解析逻辑用的百度开发者api弄的
> 
> https://github.com/hmjz100/Online-disk-direct-link-download-assistant/blob/b008fa368fbf8af30b46a69404e7bb0444261c4c/config/config.json#L8
> 
> 
> 估计这个申请的应用直接被百度删了 所以解析不了了

有办法解决吗，比如自己申请一个开发者账号然后进行解析？

**Comment by LaelLuo** [comment]
> > 很简单的原因 解析逻辑用的百度开发者api弄的
> > https://github.com/hmjz100/Online-disk-direct-link-download-assistant/blob/b008fa368fbf8af30b46a69404e7bb0444261c4c/config/config.json#L8
> > 
> > 估计这个申请的应用直接被百度删了 所以解析不了了
> 
> 有办法解决吗，比如自己申请一个开发者账号然后进行解析？

不晓得 我尝试申请 看到要企业认证就没看了

**Comment by Rnreck** [comment]
> > > 很简单的原因 解析逻辑用的百度开发者api弄的
> > > https://github.com/hmjz100/Online-disk-direct-link-download-assistant/blob/b008fa368fbf8af30b46a69404e7bb0444261c4c/config/config.json#L8
> > > 
> > > 估计这个申请的应用直接被百度删了 所以解析不了了
> > 
> > 
> > 有办法解决吗，比如自己申请一个开发者账号然后进行解析？
> 
> 不晓得 我尝试申请 看到要企业认证就没看了

好吧，那确实不好搞

**Comment by hmjz100** [comment]
v1.0.9 已修复~
