### ISSUE TITLE
RPC一次创建了4个任务

### ISSUE THREAD

**Issue by TomYule** [hmjz100/Online-disk-direct-link-download-assistant#9]
RPC一次创建了4个任务
[www.aliyundrive.com/s/QUEJKWEpPQE](http://www.aliyundrive.com/s/QUEJKWEpPQE)

**Comment by davidtwchn** [comment]
我试了一下没这问题。
![Capture_001](https://user-images.githubusercontent.com/34048833/233526784-df8a8252-7a80-4695-9d3a-a5ec7f1f9bce.jpg)

**Comment by TomYule** [comment]
这个问题一直存在
