### ISSUE TITLE
阿里云盘无法获取下载地址

### ISSUE THREAD

**Issue by z51885188** [hmjz100/Online-disk-direct-link-download-assistant#90]
阿里云盘RPC下载推送请求，RPC服务端返回400报错为No URI to download

**Comment by linjialiang** [comment]
阿里云盘 无法下载

**Comment by hanxuyuan** [comment]
同，阿里云盘推送RPC失败了……

另外，Greasy Fork上面有恶意刷差评的水平，请大大不要放在心上，有眼睛的人都看得见

**Comment by zzq206** [comment]
阿里云盘里的各种下载都不能正常使用。
![image](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/30394904/ca3f2da3-fc1e-49da-aff3-8cec9b3d3ded)

**Comment by tcstory** [comment]
遇到同样的问题

**Comment by zttzml** [comment]
遇到同样问题 期待解决求求了

**Comment by 18353923757** [comment]
阿里云盘API下载完成后不弹出浏览器保存框

**Comment by Beixiaobai** [comment]
的确，如上述朋友所述；阿里云盘无法成功推送链接、但是夸克盘是可以推送并成功下载

**Comment by IsUnderAchiever** [comment]
![1](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/115987153/2ef09127-5215-4a04-91ef-0418f0a33344)
发送链接失败
![2](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/115987153/39bdafac-8e2b-4ca6-9e1d-7037a67272d4)
但是测试Motrix的连接却显示成功
