### ISSUE TITLE
Mac OS Edge 夸克没有按钮 

### ISSUE THREAD

**Issue by shenyx110** [hmjz100/Online-disk-direct-link-download-assistant#94]
![截屏2024-06-11 17 49 14](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/132644153/329c80a9-8fb0-4df4-9941-9388624ec663)
![截屏2024-06-11 17 49 27](https://github.com/hmjz100/Online-disk-direct-link-download-assistant/assets/132644153/b2d04641-f5e1-4b61-a137-39359d86a707)

**Comment by wel-come** [comment]
**资本出手了，各种网盘解析G了个七七八八了**
